# Generated by Django 4.2.1 on 2023-05-18 18:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Kunde",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vorname", models.CharField(max_length=50)),
                ("nachname", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telefonnummer", models.CharField(max_length=15, unique=True)),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                ("aktualisiert_am", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Mitarbeiter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("agent", "Agent"),
                            ("manager", "Manager"),
                            ("support", "Support"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("geburtsdatum", models.DateField(null=True)),
                ("einstellungsdatum", models.DateField(null=True)),
                (
                    "telefonnummer",
                    models.CharField(max_length=15, null=True, unique=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Versicherungsvertrag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vertragsnummer", models.CharField(max_length=20, unique=True)),
                ("startdatum", models.DateField()),
                ("enddatum", models.DateField()),
                (
                    "monatlicher_beitrag",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("abgeschlossen_am", models.DateTimeField(auto_now_add=True)),
                ("aktualisiert_am", models.DateTimeField(auto_now=True)),
                (
                    "kunde",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="versicherung.kunde",
                    ),
                ),
                (
                    "mitarbeiter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="versicherung.mitarbeiter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Schadensfall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("beschreibung", models.TextField()),
                (
                    "schadenshoehe",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("offen", "Offen"),
                            ("bearbeitet", "Bearbeitet"),
                            ("abgeschlossen", "Abgeschlossen"),
                        ],
                        max_length=50,
                    ),
                ),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                ("aktualisiert_am", models.DateTimeField(auto_now=True)),
                (
                    "versicherungsvertrag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="versicherung.versicherungsvertrag",
                    ),
                ),
            ],
        ),
    ]
